id: AB1FBDFA3
title: Condensed Daily Practice of The Heart Essence of the Sublime Lady of Immortality
type: translation
pechas:
- I9485A7F9
- IB0B9FC97
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:49:22.845456
  last_modified_at: 2023-01-04 11:49:22.845461
  collections:
  - Dudjom Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I9485A7F9/D9C2: 0AAA
  IB0B9FC97/FEC2: 0AAA
